#' Dump data.table modification script
#'
#' Dump data.table modification script
#' @param x `dcmodify::modifier()` object with the modification rules
#' @param name `character` name of data.table to be used.
#' @param file where should the generated file be written?
#' @export
dump_dt <- function(x, name = "dat", file = stdout()){
  header <- paste0("# ", c(
    "####################################",
    "Generated by dcmodifydt, do not edit",
    sprintf("dcmodify version: %s", utils::packageVersion("dcmodify")),
    sprintf("dcmodifydt version: %s", utils::packageVersion("dcmodifydt")),
    "####################################"
  ))

  line <- if (name != "dat") paste0("dat <- ", name, "\n")

  asgns <- sapply(x$assignments(), function(a){
    # text translation of a
    dt_assign_char(dt_assign(a))
  })

  txt <- c( header
          , sprintf("# ensure that sourcing the file only affects '%s'", name)
          , "local({"
          , paste0("  ", line)
          , paste0("  ", asgns)
          , "})"
          )
  writeLines(txt, file)
  invisible(txt)
}
